### ISSUE TITLE
protect repo with PR from code owners

### ISSUE THREAD

**Issue by kagawaa** [kentik/config-snippets#2]
https://github.community/t5/Support-Protips/Best-practices-for-protected-branches/ba-p/10224 
https://help.github.com/en/articles/about-code-owners

**Comment by grrrrreg** [comment]
Hey @kagawaa - I think you have admin rights on this repo, can you help setting this up? Because I'm way out of my depth w/ GitHub...

**Comment by kagawaa** [comment]
i did it with this setting. 

![image](https://user-images.githubusercontent.com/25144/54732915-94e91380-4b3a-11e9-9646-3136151e8fbf.png)
