### ISSUE TITLE
Silver Peak

### ISSUE THREAD

**Issue by jryburn** [kentik/config-snippets#32]
Need to add Silver Peak config examples to our repo.

**Comment by kagawaa** [comment]
@jryburn its all GUI based see https://docs.google.com/document/d/1wkHxs32EV440KK6-hx29tk6xtlsvjnnLBGJNxYjELeg/edit#heading=h.anvofzqn9wb1

**Comment by jryburn** [comment]
Could we create a SilverPeak directory, put the logo in it, and put a few of those screenshots in it? I know it sounds a little goofy to do that but what I am really trying to accomplish is someplace in our product where we can show a customer a Silver Peak logo to show we support SilverPeak as a device vendor. We can do this today with Juniper, Cisco, Palo Alto, etc. with the logo in their config directory.

**Comment by kagawaa** [comment]
we certainly can, i thought we had screenshots or written instructions in one of these configs. we'd have to check if it breaks onboarding.

**Comment by kagawaa** [comment]
this is how the manual instructions work. 
![image](https://user-images.githubusercontent.com/25144/86976717-c498a200-c116-11ea-8f25-d6ebf112e21a.png) 

@jryburn are you good with that?

**Comment by jryburn** [comment]
Makes sense to me.

**Comment by smeusekentik** [comment]
I just shared a folter with you guys that has two images, examples from
Kronos of what their console looks like. It's generic enough that we can
probably use it as a config example.

-Steve
